#!/bin/sh
verified=./scripts/verify-js
if $verified
then
    echo "Compiling less..."
    ./scripts/compile-less
    echo "Starting server..."
    # node ./src/twitter.js &
    # TODO: Check if mac os x
    # say "FoodTruckler is now online" &
    node ./src/server.js "$@"
fi
