DROP TABLE follows CASCADE;
DROP TABLE classified_as CASCADE;
DROP TABLE vendors CASCADE;
DROP TABLE users CASCADE;
DROP TABLE trucks CASCADE;
DROP TABLE photos CASCADE;
DROP TABLE uploads CASCADE;
DROP TABLE categories CASCADE;
